// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiZuhKCNor_0YNeGtfDMFzvuwm7cBLIY0',
    appId: '1:990250274126:android:046cabb559095c07c6a21f',
    messagingSenderId: '990250274126',
    projectId: 'races-b0d7b',
    storageBucket: 'races-b0d7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVhgJvt80CDP6uf2fd25rhr3haz_gmb2U',
    appId: '1:990250274126:ios:b482a4cf77f5b1c1c6a21f',
    messagingSenderId: '990250274126',
    projectId: 'races-b0d7b',
    storageBucket: 'races-b0d7b.appspot.com',
    androidClientId: '990250274126-qtd88k9mgtfgu8u4ba9v3t120kfm8jj4.apps.googleusercontent.com',
    iosClientId: '990250274126-q1e8g52fis2fv189le8ucsepfss8ar5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.races',
  );
}
